# 创建数据库
CREATE DATABASE IF NOT EXISTS robin_test;
USE robin_test;

SET FOREIGN_KEY_CHECKS=0;

# 创建对应的表格
#DROP TABLE IF EXISTS t_person;
CREATE TABLE IF NOT t_person(
    id BIGINT(18) NOT NULL AUTO_INCREMENT,
    name VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '姓名',
    ctime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime datetime DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (id),
		UNIQUE KEY id_unique(id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='用户表';